#!/usr/bin/env node
// Regenerates the GENERATED tool-list block in skills/dropthis-mcp/references/tools.md
// from the REAL JSON Schemas returned by the published @dropthis/mcp stdio server.
// We drive `dist/bin.cjs` over stdio with a tools/list JSON-RPC request (the same call an
// MCP client makes), so tool names, input fields, and required-ness can never drift from
// what the agent actually sees. We do NOT scrape src/tools.ts text and do NOT execute zod.
// The server starts with a dummy DROPTHIS_API_KEY (auth is only checked on a real tool call),
// so this runs fully offline and deterministically.
// Usage:
//   npm run gen:tools                 # write the block
//   node scripts/gen-tools.mjs --check     # exit 1 if stale
import { spawn } from "node:child_process";
import { createRequire } from "node:module";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const DOC = resolve(here, "../skills/dropthis-mcp/references/tools.md");
const BEGIN = "<!-- BEGIN GENERATED TOOLS -->";
const END = "<!-- END GENERATED TOOLS -->";
const require = createRequire(import.meta.url);

// Resolve the @dropthis/mcp bin from the repo's own node_modules (pinned devDependency).
function resolveMcpBin() {
  const pkgPath = require.resolve("@dropthis/mcp/package.json");
  const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
  const rel = typeof pkg.bin === "string" ? pkg.bin : pkg.bin["dropthis-mcp"];
  return resolve(dirname(pkgPath), rel);
}

function listTools() {
  return new Promise((resolveP, rejectP) => {
    const child = spawn(process.execPath, [resolveMcpBin()], {
      env: { ...process.env, DROPTHIS_API_KEY: "sk_gen_dummy" },
      stdio: ["pipe", "pipe", "pipe"],
    });
    let out = "";
    let err = "";
    child.stdout.on("data", (d) => (out += d.toString()));
    child.stderr.on("data", (d) => (err += d.toString()));
    const send = (o) => child.stdin.write(`${JSON.stringify(o)}\n`);
    send({ jsonrpc: "2.0", id: 1, method: "initialize", params: { protocolVersion: "2024-11-05", capabilities: {}, clientInfo: { name: "gen-tools", version: "0" } } });
    send({ jsonrpc: "2.0", method: "notifications/initialized", params: {} });
    send({ jsonrpc: "2.0", id: 2, method: "tools/list", params: {} });
    const timer = setTimeout(() => {
      child.kill();
      for (const line of out.split("\n").filter(Boolean)) {
        try {
          const msg = JSON.parse(line);
          if (msg.id === 2 && msg.result) return resolveP(msg.result.tools);
        } catch {}
      }
      rejectP(new Error(`tools/list produced no result. stderr: ${err.slice(0, 400)}`));
    }, 5000);
    child.on("error", (e) => { clearTimeout(timer); rejectP(e); });
  });
}

function fieldList(schema) {
  const props = schema && schema.properties ? Object.keys(schema.properties) : [];
  if (props.length === 0) return "(none)";
  const required = new Set(schema.required || []);
  return props.map((p) => `\`${p}\`${required.has(p) ? " (required)" : ""}`).join(", ");
}

const tools = (await listTools()).sort((a, b) => a.name.localeCompare(b.name));
const lines = [
  BEGIN,
  "",
  "> Auto-generated by `scripts/gen-tools.mjs` from the live `@dropthis/mcp` `tools/list` schemas. Do not edit by hand.",
  "",
];
for (const t of tools) {
  lines.push(`### \`${t.name}\``);
  lines.push(`Inputs: ${fieldList(t.inputSchema)}`, "");
}
lines.push(END, "");
const block = lines.join("\n");

const doc = readFileSync(DOC, "utf8");
let next;
if (doc.includes(BEGIN) && doc.includes(END)) {
  next = doc.replace(new RegExp(`${BEGIN}[\\s\\S]*?${END}\\n?`), block);
} else {
  next = `${doc.trimEnd()}\n\n${block}`;
}

if (process.argv.includes("--check")) {
  if (doc !== next) {
    console.error("tools.md GENERATED block is stale. Run: npm run gen:tools");
    process.exit(1);
  }
  console.log("tools.md generated block up to date.");
} else {
  writeFileSync(DOC, next);
  console.log(`Updated GENERATED block in ${DOC}`);
}
